### ISSUE TITLE
Separate birthday and reminder configuration

### ISSUE THREAD

**Issue by grimnight** [xplshn/Britto#2]
In my case I am unlikely to change birthday configurations, other than to add new ones.
Currently having both in the same file could be problematic for scripts or TUIs that add new reminders, which could accidentally break the configuration file.

So I'm suggesting either another file for reminders or an entire directory of files for easy adding.

Adding another file or directory would require moving the configuration to `$XDG_CONFIG_HOME/Britto`.

**Comment by xplshn** [comment]
I think I'll just make Britto read all files under `$XDG_CONFIG_HOME/Britto`, so that you can choose to add birthdays and other types of reminders wherever you like. Does that work for you?

**Comment by grimnight** [comment]
That would work for me.

Thank you.

**Comment by xplshn** [comment]
Excellent, going to work on it then

**Comment by grimnight** [comment]
Just compiled the latest code and it's looking pretty good.
But, it doesn't seem to load other files from `$XDG_CONFIG_HOME/britto`, only `britto.toml`.
Also, is it possible to turn off [Message]?

[Message]: https://github.com/xplshn/Britto/blob/master/britto.go#L191

**Comment by xplshn** [comment]
> Just compiled the latest code and it's looking pretty good. But, it doesn't seem to load other files from `$XDG_CONFIG_HOME/britto`, only `britto.toml`. Also, is it possible to turn off [Message](https://github.com/xplshn/Britto/blob/master/britto.go#L191)?

My bad for not doing throught testing, I'll get back to this in a moment. srry
